### ISSUE TITLE
Flip the ACL structure from path.role.verb to role.path.verb

### ISSUE THREAD

**Issue by yaronyg** [thaliproject/salti#3]
The current structure is sub-optimal for our needs for two reasons. First, it requires mixing acls together. In other words if I want to define role 1 and role 2 we have to define one acl with both roles in it defined together.

``` JSON
{
  "path" : "/",
   "roles" : [
      { "role": "admin", "verbs": ["GET", "PUT"] },
      { "role": "user", "verbs": ["GET"] }
   ]
}, {
  "path": "/foo",
  "roles" : [
      { "role": "admin", "verbs": ["GET", "DELETE"] },
      { "role": "user", "verbs": ["GET"] }
   ]
}
```

So to understand what a particular role is doing we have to walk through each and every path and try to keep in our mind which role is which. It also means that people can't define roles separately and then bring them together. So if one was using different modules with different roles there is no way to just pull in the role. Instead one has to write code to parse it into a single ACL.

Second, the current structure is also inefficient in that we have a relatively small number of roles but a large number of paths. But by putting path at the top of the structure we are constantly forced to repeat the same roles over and over again.

What we would rather have is:

``` JSON
{
  "ACLs": 
  {
     "admin": {
         "/": ["GET", "PUT"],
         "/foo": ["GET", "DELETE"]
      },
      "user": {
         "/": ["GET"],
         "/foo": ["GET"]
      }
}
```

With this structure all the paths and verbs for a role are expressed in a very compact format and we can have different modules define different roles and very easily bring them together into a single ACL that we enforce at run time.

**Comment by cicorias** [comment]
this was done..
